### ISSUE TITLE
slides on home page

### ISSUE THREAD

**Issue by fahad-israr** [helloworld-iiitt/iiitt#10]
-  the data for slides on the home page is being taken from an array
- move that to a JSON file as for the other components

**Comment by anoopjt** [comment]
Can a set of n images be added, and pick x randomly.

Or have images added with description, and active true and false can be configured

**Comment by fahad-israr** [comment]
Currently we have this config that will move to json  file: images={[{'name':'IIIT Trichy','path':'orion.jpg'},{'name':'#Ha[.sh] \'19' ,'path':'hash.jpg'},{'name':'director','path':'003.jpeg'}]}/
each image has two components:
- name: that acts as description and appears on the slide (as you could see)
- path: the name of image file /images folder (will expect in /images/slide to be appropriate)
- Now coming to choosing random or setting true/false?Yes either can be done very easily..but since we will atmost have 8-10 images why not chosse ourself and put in the .json file itself.
- Reasons: 
- Choosing randomly will not be appropriate when there are images that  we definitely want to show/flaunt.  
- True/False is as equivalent as removing the entry from json file.
- But still we can do either of these if we need

**Comment by dinskid** [comment]
What would you like me to do? Should I add the logic for picking it randomly, or should I create an interface to add and remove entries from the json file?

**Comment by fahad-israr** [comment]
Currently, just make the list configurable using JSON file like for the navbar.
`home-carousel.json` can be the file

**Comment by fahad-israr** [comment]
infact avoid special characters
use `homeCarousel.json`
