### ISSUE TITLE
Admission Page

### ISSUE THREAD

**Issue by fahad-israr** [helloworld-iiitt/iiitt#25]
- like http://www.iiitt.ac.in/admission

Dropdown menu  for Admission (in navbar) should have the following items and each item should have  page as described:
- Procedure: All content from beginning up till Opening and Closing Ranks
- Fee Structure: Currently link to pdf as on `iiitt.ac.in` (create folder /documents for pdf like we've done for /images and /json)
-Forms: Simple page with forms links to download
- Anti Ragging Committee:A page with some image of "Say no to ragging" or "ragging is a crime etc" 
 and then (1) Link to Anti Ragging Portal https://www.antiragging.in/ and (2)The Anti Ragging Committee(The PDF as on iiit website) 
- Contact: (like on iiitt.ac.in)

**Comment by dinskid** [comment]
Currently admission has undergraduate and Ph.D. under it. Should I replace it with this, or should it be submenu to undergraduate?

**Comment by fahad-israr** [comment]
Replace with this submenu as this is what there on iiitt.ac.in/admission
Later we'll look into it

**Comment by dinskid** [comment]
Forms come under fee structure page, or is it a separate page

**Comment by fahad-israr** [comment]
separate!!

**Comment by dinskid** [comment]
Can this issue be closed?
