### ISSUE TITLE
people 

### ISSUE THREAD

**Issue by fahad-israr** [helloworld-iiitt/iiitt#7]
- faculty and staff page as on origal site
- Data from JSON
- No hardcoding

**Comment by dinskid** [comment]
Created PR!

**Comment by dinskid** [comment]
What about the footer? It doesn't stick to the bottom of the page. An easy workaround could be to add a custom css rule to all the pages where the content is less than the screen size as bottom: 0. But if there is a better way, that you know of we can do that.
